name: flutter analyze
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-18.04
    steps:
    # Set up Flutter.
    - name: Clone Flutter repository with master channel
      uses: subosito/flutter-action@4389e6cbc6cb8a4b18c628ff96ff90be0e926aa8
      with:
        channel: master
    - run: flutter doctor -v

    # Checkout code and get packages.
    - name: Check out repository code
      uses: actions/checkout@v2
    - run: flutter pub get

    # Analyze, check formatting, and run unit tests.
    - run: flutter analyze
    - name: Ensure the Dart code is formatted correctly
      run: flutter format --set-exit-if-changed --dry-run .
    # - name: Run Flutter unit tests
    #   run: flutter test

    - name: Dump github context
      run:   echo "$(basename $GITHUB_REPOSITORY)"
      shell: bash
      env:
       GITHUB_CONTEXT: ${{ github.repository }}
